name: econsultation
description: "Application de gestion des consultations médicales — Master e-Santé"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  # État
  provider: ^6.0.0

  # Données locales
  hive_flutter: ^1.1.0

  # Réseau
  http: ^1.2.0
  connectivity_plus: ^6.0.0

  # Sécurité
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2

  # Graphiques
  fl_chart: ^0.69.0

  # Utilitaires
  intl: ^0.20.2
  uuid: ^4.3.3

  # Export PDF
  pdf: ^3.11.1
  printing: ^5.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
